// Generated by scripts/deploy.js — safe to gitignore
window.TICKET_DEPLOYMENT = {
  ticketTokenAddress: "0xd67051f294e8ACEA08dcbDe513659f073cf06668",
  vendorAddress: "0x906b4a0773828D6528329ED486ae59F9e08cd5bf",
  ticketPriceWei: "10000000000000000",
};
