// Generated by scripts/deploy.js — safe to gitignore
window.TICKET_DEPLOYMENT = {
  ticketTokenAddress: "0xC624895c31FE16b552ac7966C73039276B95a888",
  vendorAddress: "0x906b4a0773828D6528329ED486ae59F9e08cd5bf",
  ticketPriceWei: "10000000000000000",
};
