const fs = require("fs");
const path = require("path");

async function main() {
  const [deployer] = await ethers.getSigners();

  const vendorAddress =
    process.env.VENDOR_ADDRESS && process.env.VENDOR_ADDRESS.startsWith("0x")
      ? process.env.VENDOR_ADDRESS
      : deployer.address;

  const ticketPriceEth = process.env.TICKET_PRICE_ETH || "0.01";
  const ticketPriceWei = ethers.parseEther(ticketPriceEth);

  const TicketToken = await ethers.getContractFactory("TicketToken");
  const token = await TicketToken.deploy(
    "Event Ticket",
    "ETIX",
    ticketPriceWei,
    vendorAddress,
    deployer.address
  );
  await token.waitForDeployment();

  const address = await token.getAddress();
  const network = await ethers.provider.getNetwork();

  console.log("TicketToken deployed to:", address);
  console.log("Chain ID:", network.chainId.toString());
  console.log("Vendor (return-to address):", vendorAddress);
  console.log("Ticket price (wei):", ticketPriceWei.toString());

  const artifactPath = path.join(__dirname, "..", "deployments", `chain-${network.chainId}-TicketToken.json`);
  const artifact = {
    contractName: "TicketToken",
    address,
    chainId: Number(network.chainId),
    vendorAddress,
    ticketPriceWei: ticketPriceWei.toString(),
    deployedAt: new Date().toISOString(),
    deployer: deployer.address,
  };
  fs.mkdirSync(path.dirname(artifactPath), { recursive: true });
  fs.writeFileSync(artifactPath, `${JSON.stringify(artifact, null, 2)}\n`, "utf8");
  console.log("Wrote:", artifactPath);

  const incPath = path.join(__dirname, "..", "frontend", "src", "js", "deployed.inc.js");
  const incBody = `// Generated by scripts/deploy.js — safe to gitignore\nwindow.TICKET_DEPLOYMENT = {\n  ticketTokenAddress: "${address}",\n  vendorAddress: "${vendorAddress}",\n  ticketPriceWei: "${ticketPriceWei.toString()}",\n};\n`;
  fs.writeFileSync(incPath, incBody, "utf8");
  console.log("Wrote:", incPath);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
